version: '3.8'

services:
  web:
    build:
      context: ./front-go-chat-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - web


volumes:
  postgres_data:
